version: '3.8'
services:
  django:  &django
    container_name: academia_django
    environment:
      - DEBUG=${DEBUG}
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: >
                sh -c "
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000
                "
    volumes:
    - .:/code
    - media_volume:/code/media
    ports:
    - 8000:8000
    - 3001:3001
    depends_on:
    - db  
  weasyprint:
    container_name: academia_weasyprint
    image: 4teamwork/weasyprint
    ports:
      - 5001:5001
  db:
    container_name: academia_db
    image: postgres:16
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: academia
      PGPORT: 5434
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  media_volume:
  pgdata:
